### PR TITLE
add vmi_get_va_pages

### PR DESCRIPTION
**Pull request by Wenzel**
Implement `vmi_get_va_pages` from `libvmi_extra.h`

- removed `glib_build.py`, and integrated the glib functions into the main libvmi CFFI module
- add `get_va_pages` in `libvmi.py`
- add class `PageInfo` in `libvmi.py`

### CODE REVIEW

**Comment by Wenzel** [comment]
Ready for review.
@tklengyel @smaresca

**Comment by Wenzel** [comment]
~~~Python
            dtb = vmi.get_vcpu_reg(CR3, 0)
            va_pages = vmi.get_va_pages(dtb)
            for page in va_pages:
                print('Page: dtb {} vaddr {} size {}'.format(
                    hex(page.dtb),
                    hex(page.vaddr),
                    hex(page.size)))
~~~

Result
~~~
Page: dtb 0x0 vaddr 0x76f21000 size 0x1000
Page: dtb 0x0 vaddr 0x76f20000 size 0x1000
Page: dtb 0x0 vaddr 0x76f1d000 size 0x1000
Page: dtb 0x0 vaddr 0x76f1c000 size 0x1000
Page: dtb 0x0 vaddr 0x76f1b000 size 0x1000
Page: dtb 0x0 vaddr 0x76f1a000 size 0x1000
Page: dtb 0x0 vaddr 0x76f19000 size 0x1000
Page: dtb 0x0 vaddr 0x76f18000 size 0x1000
Page: dtb 0x0 vaddr 0x76f17000 size 0x1000
Page: dtb 0x0 vaddr 0x76f16000 size 0x1000
Page: dtb 0x0 vaddr 0x76e10000 size 0x1000
Page: dtb 0x0 vaddr 0x7f000 size 0x1000
Page: dtb 0x0 vaddr 0x7e000 size 0x1000
Page: dtb 0x0 vaddr 0x7d000 size 0x1000
Page: dtb 0x0 vaddr 0x7c000 size 0x1000
Page: dtb 0x0 vaddr 0x7b000 size 0x1000
Page: dtb 0x0 vaddr 0x7a000 size 0x1000
Page: dtb 0x0 vaddr 0x79000 size 0x1000
Page: dtb 0x0 vaddr 0x78000 size 0x1000
Page: dtb 0x0 vaddr 0x77000 size 0x1000
Page: dtb 0x0 vaddr 0x76000 size 0x1000
Page: dtb 0x0 vaddr 0x75000 size 0x1000
Page: dtb 0x0 vaddr 0x74000 size 0x1000
~~~

Why the `dtb` field is always empty ??
I need to check if it's the same with a C test file.

**Comment by smaresca** [comment]
I would agree that result seems incorrect

**Comment by Wenzel** [comment]
@smaresca it seems there is an issue in Libvmi `vmi_get_va_pages`:

~~~C
    /* initialize the libvmi library */
    if (VMI_FAILURE == vmi_init_complete(&vmi, name, VMI_INIT_DOMAINNAME, NULL, VMI_CONFIG_GLOBAL_FILE_ENTRY, NULL, NULL)) {
        printf("Failed to init LibVMI library.\n");
        return 1;
    }

    printf("LibVMI init succeeded!\n");

    uint64_t dtb;
    vmi_get_vcpureg(vmi, &dtb, CR3, 0);
    GSList *va_pages = vmi_get_va_pages(vmi, dtb);
    GSList *loop = va_pages;

    while (loop)
    {
        page_info_t *page = loop->data;
        printf("vaddr: %p dtb: %p\n", page->vaddr, page->dtb);
        loop = loop->next;
    }
    return 0;
~~~

~~~
vaddr: 0x42000 dtb: (nil)
vaddr: 0x41000 dtb: (nil)
vaddr: 0x40000 dtb: (nil)
vaddr: 0x32000 dtb: (nil)
vaddr: 0x31000 dtb: (nil)
vaddr: 0x30000 dtb: (nil)
vaddr: 0x2f000 dtb: (nil)
vaddr: 0x2e000 dtb: (nil)
vaddr: 0x2d000 dtb: (nil)
vaddr: 0x2c000 dtb: (nil)
vaddr: 0x2b000 dtb: (nil)
vaddr: 0x2a000 dtb: (nil)
vaddr: 0x29000 dtb: (nil)
vaddr: 0x28000 dtb: (nil)
vaddr: 0x27000 dtb: (nil)
vaddr: 0x26000 dtb: (nil)
vaddr: 0x25000 dtb: (nil)
vaddr: 0x24000 dtb: (nil)
vaddr: 0x23000 dtb: (nil)
vaddr: 0x22000 dtb: (nil)
vaddr: 0x21000 dtb: (nil)
vaddr: 0x20000 dtb: (nil)
vaddr: 0x1f000 dtb: (nil)
vaddr: 0x1e000 dtb: (nil)
vaddr: 0x1d000 dtb: (nil)
vaddr: 0x1c000 dtb: (nil)
vaddr: 0x1b000 dtb: (nil)
vaddr: 0x1a000 dtb: (nil)
vaddr: 0x19000 dtb: (nil)
vaddr: 0x18000 dtb: (nil)
vaddr: 0x17000 dtb: (nil)
vaddr: 0x16000 dtb: (nil)
vaddr: 0x15000 dtb: (nil)
vaddr: 0x14000 dtb: (nil)
vaddr: 0x13000 dtb: (nil)
vaddr: 0x12000 dtb: (nil)
vaddr: 0x11000 dtb: (nil)
vaddr: 0x10000 dtb: (nil)
~~~

**Comment by Wenzel** [comment]
@smaresca i opened an issue on libvmi about this empty dtb field, this is not related to `libvmi/python`.
this PR is ready for review and approval :)

**Comment by Wenzel** [comment]
I will merge this PR as it contains changes that I need, and the changes are quite straightforward.

**Pull request merged**
